// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using YemekTenceremCom.Data;

namespace YemekTenceremCom.Migrations
{
    [DbContext(typeof(YemekContext))]
    [Migration("20180222162919_YorumTablosuEkle")]
    partial class YorumTablosuEkle
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("YemekTenceremCom.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("KAdi")
                        .IsRequired();

                    b.Property<string>("Sifre")
                        .IsRequired();

                    b.Property<string>("Turu");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("YemekTenceremCom.Models.Yemek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ad");

                    b.Property<string>("Hazirlanisi");

                    b.Property<string>("Malzemeler");

                    b.Property<string>("Resim");

                    b.HasKey("Id");

                    b.ToTable("Yemekler");
                });

            modelBuilder.Entity("YemekTenceremCom.Models.Yorum", b =>
                {
                    b.Property<int>("YorumId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("YorumMetni");

                    b.HasKey("YorumId");

                    b.ToTable("Yorumlar");
                });
#pragma warning restore 612, 618
        }
    }
}
